name: Master Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm coverage
      run: |
        set -e
        npm install
        npm run coverage-to-codacy
        cov=$(curl -s -X GET https://api.codacy.com/2.0/project \
          -H 'Accept: application/json' \
          -H 'project_token: ${{ secrets.CODACY_TOKEN }}' | jq -r '.commit.commit.grade')
        echo $cov
        if [[ "$cov" == "A" ]]
          then
            echo -e "\e[1;42m Grade $cov is ok. Build will continue. \e[0m"
          else
            echo -e "\e[1;31m Grade $cov is below the expected and the build will stop. \e[0m"
        fi
      env:
        CI: true

  
