name: Master Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm coverage
    - shell: bash
      run: |
        set -e
        npm install
        npm run coverage-to-codacy
        cov=$(curl -s -X GET https://api.codacy.com/2.0/project \
          -H 'Accept: application/json' \
          -H 'project_token:  ${{ secrets.CODACY_TOKEN }}' | jq -r '.commit.commit.coverage')
        echo $cov
        if [[ "$cov" -lt "20" ]]
          then
            echo "Coverage not acceptable"
            exit 1
          else
            echo "All done"
        fi
      env:
        CI: true

  
