# This is a basic workflow to help you get started with Actions

name: Report Incident

on:
  workflow_dispatch:
    inputs:
      timeToFix:
        description: 'How long was the incident in minutes?'
        required: true
        default: '30'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Report Changes and Deployment to Pulse
        run: |
          curl -fsSL -o pulse-event-cli https://dl.bintray.com/codacy/pulse/event-cli/1.7.3/pulse-event-cli_linux_386/pulse-event-cli
          chmod +x pulse-event-cli
          ./pulse-event-cli push incident \
            --api-key "${{ secrets.PULSE_TOKEN }}" \
            --identifier "$(date +%s)" \
            --timestampCreated "$(date +%s)" \
            --timestampResolved "$(date +%s)" \
            --system "nodeproject"
